// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfghwldvhoxibanhuvhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmZ2h3bGR2aG94aWJhbmh1dmhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MzQ4OTUsImV4cCI6MjA2ODMxMDg5NX0.PQHKY-duvJBFvbpSjAAKgGh69GILHORqzst2nR6pMXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});